# yaml-language-server: $schema=./lib/config.schema.json

locales:
  /:
    lang: zh-CN
    langName: EN
    title: Mister-Hope | Portfolio
    description: The personal portfolio of Mister-Hope, a front-end developer and physic teacher.
    ui:
      themeToggle: Toggle Theme
      contact: Contact

    hero:
      name: Mister-Hope
      welcome: ğŸ‘‹ Hi there, I am
      titles:
        - High School Physics Teacher
        - Front-end Developer
        - Open Source Contributor
        - A Lifelong Learner
      avatar: /avatar.avif
      bgImage: /bg.avif
      medias:
        - icon: fa7-brands:blogger
          name: Blog
          link: https://mister-hope.com

        - icon: fa7-brands:github
          name: GitHub
          link: https://github.com/Mister-Hope

        - icon: fa7-brands:linkedin-in
          name: LinkedIn
          link: https://www.linkedin.com/in/mister-hope/

        - icon: simple-icons:zhihu
          name: Zhihu
          link: https://www.zhihu.com/people/mister-hope

        - icon: fa7-brands:steam
          name: Steam
          link: https://steamcommunity.com/id/Mister_Hope

        - icon: fa7-brands:x-twitter
          name: X
          link: https://x.com/Mister_Hope

    navbar:
      links:
        - label: Profile
          anchor: "#profile"
        - label: Experience
          anchor: "#experience"
        - label: Projects
          anchor: "#projects"
        - label: Theses
          anchor: "#theses"

    sections:
      - type: profile
        id: profile
        title: Profile
        icon: user-tie
        data:
          fields:
            - title: Name
              icon: user
              value: BoWang Zhang

            - title: Affiliation
              icon: building-columns
              value: Northeast YuCai School

            - title: Interests
              icon: heart
              value:
                - Coding
                - Gaming
                - Music

          contacts:
            - label: Email
              value: mister-hope@outlook.com
              icon: envelope

            - label: Telegram
              value: Mister_Hope
              icon: fa7-brands:telegram
              link: https://t.me/Mister_Hope

          slogan: Where there is light, there is hope.

      - type: experience
        id: experience
        title: Experience
        icon: graduation-cap
        data:
          - type: work
            place: Northeast YuCai School, China
            time: Aug. 2025 - Present
            title: Physics Teacher, High School Department
            content: Teaching physics for students from class 2513.

          - type: volunteer
            place: ChangChun, China
            time: Jan. 2025 - Jul. 2025
            title: Full-time open source contributor
            content: Building open source projects like [VuePress](https://vuejs.press/) and [markdown-it plugins](https://mdit-plugins.github.io/).

          - type: study
            place: Northeast Normal University, School of Physics, Chain
            time: Sep. 2021 - Dec. 2024
            title: Master of Science
            content: study theoretical physics with Prof. [XueXi Yi](https://cqs.nenu.edu.cn/)

          - type: volunteer
            place: AnShan, China
            time: Jul. 2020 - Aug. 2021
            title: Full-time open source contributor
            content: Building open source projects like [VuePress Theme Hope](https://theme-hope.vuejs.press/) and [Waline](https://waline.js.org/).

          - type: study
            place: Northeast Normal University, School of Physics, China
            time: Sep. 2016 - June 2020
            title: Bachelor of Science, Physics
            content: Awarded the Principal's Scholarship.

      - type: cards
        id: projects
        title: Open Source Projects
        icon: book
        data:
          - title: VuePress Core ![Stars](https://img.shields.io/github/stars/vuepress/core?style=plastic&logo=github)
            logo: https://vuejs.press/images/hero.png
            description: |-
              A Vue-powered static site generator.
            category: Project
            actions:
              - text: Website
                link: https://vuejs.press
                icon: external-link
              - text: GitHub
                link: https://github.com/vuepress/core
                icon: fa7-brands:github

          - title: VuePress Ecosystem ![Stars](https://img.shields.io/github/stars/vuepress/ecosystem?style=plastic&logo=github)
            logo: https://vuejs.press/images/hero.png
            description: A collection of official VuePress plugins and themes.
            category: Project
            actions:
              - text: Website
                link: https://ecosystem.vuejs.press
                icon: external-link
              - text: GitHub
                link: https://github.com/vuepress/ecosystem
                icon: fa7-brands:github

          - title: VuePress Theme Hope ![Stars](https://img.shields.io/github/stars/vuepress-theme-hope/vuepress-theme-hope?style=plastic&logo=github)
            logo: https://theme-hope-assets.vuejs.press/logo.svg
            description: A VuePress theme with tons of featuresâœ¨
            category: Project
            actions:
              - text: Website
                link: https://theme-hope.vuejs.press
                icon: external-link
              - text: GitHub
                link: https://github.com/vuepress-theme-hope/vuepress-theme-hope
                icon: fa7-brands:github

          - title: Waline ![Stars](https://img.shields.io/github/stars/walinejs/waline?style=plastic&logo=github)
            logo: https://waline.js.org/logo.png
            description: A Simple, Safe Comment System.
            category: Project
            actions:
              - text: Website
                link: https://waline.js.org
                icon: external-link
              - text: GitHub
                link: https://github.com/walinejs/waline
                icon: fa7-brands:github

          - title: mdit-plugins ![Stars](https://img.shields.io/github/stars/mdit-plugins/mdit-plugins?style=plastic&logo=github)
            logo: https://mdit-plugins.github.io/logo.svg
            description: A collection of markdown-it plugins written in TypeScript.
            category: Project
            actions:
              - text: Website
                link: https://mdit-plugins.github.io/
                icon: external-link

              - text: GitHub
                link: https://github.com/mdit-plugins/mdit-plugins
                icon: fa7-brands:github

          - title: bcrypt-ts
            description: A bcrypt implementation in TypeScript.
            category: Project
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/bcrypt-ts
                icon: fa7-brands:github

          - title: portfolio-template
            description: A zero-code personal portfolio template.
            category: Project
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/portfolio-template
                icon: fa7-brands:github

          - title: slimsearch
            description: A compact and powerful full-text search engine for browsers and Node.js.
            category: Project
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/slimsearch
                icon: fa7-brands:github

          - title: webpack-v5-chain
            description: A chainable API tool for building and managing webpack configurations.
            category: Project
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/webpack-v5-chain
                icon: fa7-brands:github

          - title: gulp5-sass-plugin
            description: A plugin for compiling Sass in Gulp 5.
            category: Project
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/gulp5-sass-plugin
                icon: fa7-brands:github

          - title: create-codepen
            description: Create CodePen snippets via the API.
            category: Project
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/create-codepen
                icon: fa7-brands:github

          - title: rollup-plugin-resolve-shebang
            description: A Rollup plugin that parses and preserves the shebang line in entry files.
            category: Project
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/rollup-plugin-resolve-shebang
                icon: fa7-brands:github

      - type: cards
        id: theses
        title: Theses
        icon: scroll
        data:
          - title: Manipulating spectral transitions and photonic transmission in a non-Hermitian optical system through nanoparticle perturbations
            category: Phys. Rev. A 111, 063702 (2025)
            description: |-
              DOI: <https://doi.org/10.1103/PhysRevA.111.063702>
            actions:
              - text: Read Full Text
                link: https://drive.mister-hope.com/public/files/PhysRevA.111.063702.pdf
                icon: external-link

    footer:
      copyright: Â© 2025 Mister Hope. All rights reserved.
      description: Built with Love.

  /zh/:
    lang: zh-CN
    langName: ä¸­æ–‡
    title: Mister-Hope | ä½œå“é›†
    description: Mister-Hopeï¼Œä¸€åå‰ç«¯å¼€å‘è€…å’Œç‰©ç†æ•™å¸ˆçš„ä¸ªäººä½œå“é›†
    ui:
      themeToggle: åˆ‡æ¢ä¸»é¢˜
      contact: è”ç³»

    hero:
      name: Mister-Hope
      welcome: ğŸ‘‹ ä½ å¥½ï¼Œæˆ‘æ˜¯
      titles:
        - é«˜ä¸­ç‰©ç†æ•™å¸ˆ
        - å‰ç«¯å¼€å‘è€…
        - å¼€æºè´¡çŒ®è€…
        - ç»ˆèº«å­¦ä¹ è€…
      avatar: /avatar.avif
      bgImage: /bg.avif
      medias:
        - icon: fa7-brands:blogger
          name: åšå®¢
          link: https://mister-hope.com

        - icon: fa7-brands:github
          name: GitHub
          link: https://github.com/Mister-Hope

        - icon: fa7-brands:linkedin-in
          name: é¢†è‹±
          link: https://www.linkedin.com/in/mister-hope/

        - icon: simple-icons:zhihu
          name: çŸ¥ä¹
          link: https://www.zhihu.com/people/mister-hope

        - icon: fa7-brands:steam
          name: Steam
          link: https://steamcommunity.com/id/Mister_Hope

        - icon: fa7-brands:x-twitter
          name: X
          link: https://x.com/Mister_Hope

    navbar:
      links:
        - label: ä¸ªäººèµ„æ–™
          anchor: "#profile"
        - label: ç»å†
          anchor: "#experience"
        - label: é¡¹ç›®
          anchor: "#projects"
        - label: è®ºæ–‡
          anchor: "#theses"

    sections:
      - type: profile
        id: profile
        title: ä¸ªäººèµ„æ–™
        icon: user-tie
        data:
          fields:
            - title: å§“å
              icon: user
              value: å¼ ä¼¯æœ›

            - title: æ‰€å±æœºæ„
              icon: building-columns
              value: ä¸œåŒ—è‚²æ‰å­¦æ ¡

            - title: å…´è¶£
              icon: heart
              value:
                - ç¼–ç¨‹
                - æ¸¸æˆ
                - éŸ³ä¹

          contacts:
            - label: é‚®ç®±
              value: mister-hope@outlook.com
              icon: envelope

            - label: QQ
              value: "1178522294"
              icon: fa7-brands:qq

          slogan: æœ‰å…‰çš„åœ°æ–¹ï¼Œå°±æœ‰å¸Œæœ›ã€‚

      - type: experience
        id: experience
        title: ç»å†
        icon: graduation-cap
        data:
          - type: work
            place: ä¸œåŒ—è‚²æ‰å­¦æ ¡ï¼Œä¸­å›½
            time: 2025å¹´8æœˆ - ç°åœ¨
            title: é«˜ä¸­éƒ¨ç‰©ç†æ•™å¸ˆ
            content: ä»»æ•™2513ç­ç‰©ç†ã€‚

          - type: volunteer
            place: é•¿æ˜¥ï¼Œä¸­å›½
            time: 2025å¹´1æœˆ - 2025å¹´7æœˆ
            title: å…¨èŒå¼€æºè´¡çŒ®è€…
            content: å‚ä¸æ„å»º [VuePress](https://vuejs.press/zh/) å’Œ [mdit-plugins](https://mdit-plugins.github.io/zh/) æ’ä»¶ç­‰å¼€æºé¡¹ç›®ã€‚

          - type: study
            place: ä¸œåŒ—å¸ˆèŒƒå¤§å­¦ï¼Œç‰©ç†å­¦é™¢ï¼Œä¸­å›½
            time: 2021å¹´9æœˆ - 2024å¹´12æœˆ
            title: ç†å­¦ç¡•å£«
            content: åœ¨[è¡£å­¦å–œæ•™æˆ]((https://cqs.nenu.edu.cn/))æŒ‡å¯¼ä¸‹ç ”ç©¶ç†è®ºç‰©ç†ã€‚

          - type: volunteer
            place: éå±±ï¼Œä¸­å›½
            time: 2020å¹´7æœˆ - 2021å¹´8æœˆ
            title: å…¨èŒå¼€æºè´¡çŒ®è€…
            content: å‚ä¸æ„å»º [VuePress Theme Hope](https://theme-hope.vuejs.press/zh/) å’Œ [Waline](https://waline.js.org/zh/) ç­‰å¼€æºé¡¹ç›®ã€‚

          - type: study
            place: ä¸œåŒ—å¸ˆèŒƒå¤§å­¦ï¼Œç‰©ç†å­¦é™¢ï¼Œä¸­å›½
            time: 2016å¹´9æœˆ - 2020å¹´6æœˆ
            title: ç†å­¦å­¦å£«
            content: è·å¾—æ ¡é•¿å¥–å­¦é‡‘ã€‚

      - type: cards
        id: projects
        title: å¼€æºé¡¹ç›®
        icon: book
        data:
          - title: VuePress Core ![Stars](https://img.shields.io/github/stars/vuepress/core?style=plastic&logo=github)
            logo: https://vuejs.press/images/hero.png
            description: |-
              Vue é©±åŠ¨çš„é™æ€ç½‘ç«™ç”Ÿæˆå™¨ã€‚
            category: é¡¹ç›®
            actions:
              - text: ç½‘ç«™
                link: https://vuejs.press/zh/
                icon: external-link
              - text: GitHub
                link: https://github.com/vuepress/core
                icon: fa7-brands:github

          - title: VuePress Ecosystem ![Stars](https://img.shields.io/github/stars/vuepress/ecosystem?style=plastic&logo=github)
            logo: https://vuejs.press/images/hero.png
            description: VuePress å®˜æ–¹æ’ä»¶ä¸ä¸»é¢˜é›†åˆã€‚
            category: é¡¹ç›®
            actions:
              - text: ç½‘ç«™
                link: https://ecosystem.vuejs.press/zh/
                icon: external-link
              - text: GitHub
                link: https://github.com/vuepress/ecosystem
                icon: fa7-brands:github

          - title: VuePress Theme Hope ![Stars](https://img.shields.io/github/stars/vuepress-theme-hope/vuepress-theme-hope?style=plastic&logo=github)
            logo: https://theme-hope-assets.vuejs.press/logo.svg
            description: ä¸€ä¸ªå…·æœ‰å¼ºå¤§åŠŸèƒ½çš„ VuePress ä¸»é¢˜âœ¨
            category: é¡¹ç›®
            actions:
              - text: ç½‘ç«™
                link: https://theme-hope.vuejs.press
                icon: external-link
              - text: GitHub
                link: https://github.com/vuepress-theme-hope/vuepress-theme-hope
                icon: fa7-brands:github

          - title: Waline ![Stars](https://img.shields.io/github/stars/walinejs/waline?style=plastic&logo=github)
            logo: https://waline.js.org/logo.png
            description: ä¸€æ¬¾ç®€å•ã€å®‰å…¨çš„è¯„è®ºç³»ç»Ÿã€‚
            category: é¡¹ç›®
            actions:
              - text: ç½‘ç«™
                link: https://waline.js.org
                icon: external-link
              - text: GitHub
                link: https://github.com/walinejs/waline
                icon: fa7-brands:github

          - title: mdit-plugins ![Stars](https://img.shields.io/github/stars/mdit-plugins/mdit-plugins?style=plastic&logo=github)
            logo: https://mdit-plugins.github.io/logo.svg
            description: ä¸€ç»„ç”¨ TypeScript ç¼–å†™çš„ markdown-it æ’ä»¶ã€‚
            category: é¡¹ç›®
            actions:
              - text: ç½‘ç«™
                link: https://mdit-plugins.github.io/
                icon: external-link

              - text: GitHub
                link: https://github.com/mdit-plugins/mdit-plugins
                icon: fa7-brands:github

          - title: inNENU
            logo: https://innenu.com/logo.svg
            category: é¡¹ç›®
            description: 100ä¸‡å­—çš„ä¸œå¸ˆæ–°ç”ŸæŒ‡å—ã€‚
            actions:
              - text: ç½‘ç«™
                link: https://innenu.com
                icon: external-link

              - text: GitHub
                link: https://github.com/inNENU
                icon: fa7-brands:github

          - title: mptool
            logo: https://miniapp-tool.github.io/logo.svg
            description: æå…¶è½»é‡çš„å°ç¨‹åºæ¡†æ¶
            category: é¡¹ç›®
            actions:
              - text: ç½‘ç«™
                link: https://miniapp-tool.github.io
                icon: external-link
              - text: GitHub
                link: https://github.com/miniapp-tool/mptool
                icon: fa7-brands:github

          - title: bcrypt-ts
            description: bcrypt çš„ TypeScript å®ç°ã€‚
            category: é¡¹ç›®
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/bcrypt-ts
                icon: fa7-brands:github

          - title: portfolio-template
            description: é›¶ä»£ç çš„ä¸ªäººä½œå“é›†æ¨¡æ¿ã€‚
            category: é¡¹ç›®
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/portfolio-template
                icon: fa7-brands:github

          - title: slimsearch
            description: å°å·§ä¸”å¼ºå¤§çš„æµè§ˆå™¨ä¸ Node.js å…¨æ–‡æœç´¢å¼•æ“ã€‚
            category: é¡¹ç›®
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/slimsearch
                icon: fa7-brands:github

          - title: webpack-v5-chain
            description: ä¸€ä¸ªç”¨äºæ„å»ºå’Œç®¡ç† webpack é…ç½®çš„é“¾å¼ API å·¥å…·ã€‚
            category: é¡¹ç›®
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/webpack-v5-chain
                icon: fa7-brands:github

          - title: gulp5-sass-plugin
            description: ä¸€ä¸ªç”¨äºåœ¨ Gulp 5 ä¸­ç¼–è¯‘ Sass çš„æ’ä»¶ã€‚
            category: é¡¹ç›®
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/gulp5-sass-plugin
                icon: fa7-brands:github

          - title: create-codepen
            description: é€šè¿‡ API åˆ›å»º CodePen ä»£ç ç‰‡æ®µã€‚ã€‚
            category: é¡¹ç›®
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/create-codepen
                icon: fa7-brands:github

          - title: rollup-plugin-resolve-shebang
            description: è§£æå¹¶ä¿ç•™å…¥å£æ–‡ä»¶ä¸­çš„ shebang è¡Œçš„ Rollup æ’ä»¶ã€‚
            category: é¡¹ç›®
            actions:
              - text: GitHub
                link: https://github.com/Mister-Hope/rollup-plugin-resolve-shebang
                icon: fa7-brands:github

      - type: cards
        id: theses
        title: è®ºæ–‡
        icon: scroll
        data:
          - title: Manipulating spectral transitions and photonic transmission in a non-Hermitian optical system through nanoparticle perturbations
            category: Phys. Rev. A 111, 063702 (2025)
            description: |-
              DOI: <https://doi.org/10.1103/PhysRevA.111.063702>
            actions:
              - text: é˜…è¯»å…¨æ–‡
                link: https://drive.mister-hope.com/public/files/PhysRevA.111.063702.pdf
                icon: external-link

          - title: éå„ç±³å…‰å­¦ç³»ç»Ÿçš„è°ƒæ§å’ŒåŠ¨åŠ›å­¦
            category: ç¡•å£«å­¦ä½è®ºæ–‡
            actions:
              - text: é˜…è¯»å…¨æ–‡
                link: https://drive.mister-hope.com/public/files/%E7%A1%95%E5%A3%AB%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87.pdf
                icon: external-link

    footer:
      copyright: Â© 2025 Mister Hopeã€‚ä¿ç•™æ‰€æœ‰æƒåˆ©ã€‚
      description: ç”¨çˆ±æ„å»ºã€‚
